### PR TITLE
[WIP] Contributor list script

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Added python script to get ilcsoft contributor list

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Here is the current output file if I run it : 

```json
{
   "cgrefe":"Christian Grefe",
   "killenb":"Martin Killenberg",
   "mrodozov":"Mircho Rodozov",
   "ryonamin":"Ryo Yonamine",
   "epilicer":"Ercan Pilicer",
   "aliakbarebrahimi":"Ali Ebrahimi",
   "tomohikosan":"Tomohiko Tanabe",
   "YancyW":"Yancy",
   "protopopescu":"Dan Protopopescu",
   "ebrondol":"Erica Brondolin",
   "StevenGreen1":"Steven Green",
   "beyerja":"Jakob Beyer",
   "HadrienG2":"Hadrien G.",
   "rete":"Ete Remi",
   "gaede":"Frank Gaede",
   "JavierCVilla":"Javier Cervantes",
   "akiyamiyamoto":"Akiya Miyamoto",
   "libo929":"Bo Li",
   "sbinet":"Sebastien Binet",
   "simoniel":"Rosa Simoniello",
   "jlingema":"Joschka Lingemann",
   "peremato":"Pere Mato",
   "ThorbenQuast":"Thorben Quast",
   "eleogran":"Emilia Leogrande",
   "hperrey":"Hanno Perrey",
   "robervalwalsh":"Roberval Walsh",
   "jstrube":"Jan Strube",
   "jackanth":"Jack Anthony",
   "decibelcooper":"David Blyth",
   "StrahinjaLukic":"Strahinja Luki\xc4\x87",
   "shaojunlu":"Shaojun Lu",
   "chrisburr":"Chris Burr",
   "andb0t":"Andreas Maier",
   "ggarillot":"Guillaume Garillot",
   "criticanalytic":"Christoph Rosemann",
   "lgray":"Lindsey Gray",
   "bvormwald":"Benedikt Vormwald",
   "suehara":"Taikan Suehara",
   "danieljeans":"Daniel Jeans",
   "petricm":"Marko Petric",
   "andresailer":"Andre Sailer",
   "nachogargar":"Nacho Garcia",
   "loressa":"Lorena Escudero",
   "pawlikb":"Bogdan Pawlik"
}
```
I still a problem of unicode character for StrahinjaLukic that I couldn't solved.

**Comment by petricm** [comment]
What is this aimed for? But I am a bit perplexed to see `jlingema` and `JavierCVilla` which are from DD4hep but not `nikiforosnikiforou`?

**Comment by petricm** [comment]
Does this include also authors that do not have a linked github account?

**Comment by rete** [comment]
It seems that the full user name is not setup in Github. I get a None from the python query. I've skipped these ones but we should actually contact them.
The goal is to provide a full author list for a Zenodo tag.

**Comment by rete** [comment]
For non-github users I guess we have to hardcode a list of name somewhere. But I don't know where I can find the name of these people.

**Comment by petricm** [comment]
I would suggest to remove from the above list DD4hep, FCalClusterer and PandoraPFA since these are external packages of iLCSoft also DD4hep and FCalClusterer have each their own DOI.

To get a complete list of all contributors of the remaining packages it's maybe easier to just do 
```bash
git shortlog -s -n -e
```
for each directory in a HEAD install.

**Comment by rete** [comment]
Here the new list:

```json
[
   "Christian Grefe",
   "Andreas Maier",
   "Strahinja Lukic",
   "Ryo Yonamine",
   "Ali Ebrahimi",
   "Yancy",
   "Dan Protopopescu",
   "Erica Brondolin",
   "Jakob Beyer",
   "Ete Remi",
   "Frank Gaede",
   "Akiya Miyamoto",
   "Guillaume Garillot",
   "Bo Li",
   "Sebastien Binet",
   "Rosa Simoniello",
   "Thorben Quast",
   "Taikan Suehara",
   "Emilia Leogrande",
   "Hanno Perrey",
   "Roberval Walsh",
   "Jan Strube",
   "Bogdan Pawlik",
   "Martin Killenberg",
   "Tomohiko Tanabe",
   "Shaojun Lu",
   "Christoph Rosemann",
   "Benedikt Vormwald",
   "Daniel Jeans",
   "Marko Petric",
   "Andre Sailer",
   "Nacho Garcia"
]
```

**Comment by petricm** [comment]
There will always be duplicate entries since people have changed their e-mail address... and you have to edit this by hand.

What I proposed before is this:
```bash
#!/bin/bash

function getAuthor {
  cd $1/HEAD/
  git shortlog -s -n -e | awk '{$1=""}1'
  cd ../..
}

getAuthor aidaTT
getAuthor CED
getAuthor CEDViewer
getAuthor ClicPerformance
getAuthor Clupatra
....
```
execute this script on a HEAD install and then pipe `| sort | uniq`

**Comment by rete** [comment]
@gaede Can you provide the full script(s) that you have used to the final list. You've posted the python script but not the previous command. It should actually replace my script with these ones.

**Comment by gaede** [comment]
I have pushed my scripts to this PR. See https://github.com/iLCSoft/iLCInstall/blob/32bacca1c688d57feef8c73186bb82c597a8c01a/scripts/remove_duplicate_authors.py#L2-L20
for how to run them.  They are rather raw right now and could potentially be made nicer ...

**Comment by rete** [comment]
OK. Let's go for this for now and see for further improvement later

**Pull request merged**
