### PR TITLE
Dockerfiles with CVMFS installation

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Provide Dockerfile for CVMFS installation based on SL6
- Image accessible here: https://hub.docker.com/repository/docker/ilcsoft/ilcsoft-cvmfs-sl6
- Run it with:
```shell
docker run -it --privileged ilcsoft/ilcsoft-cvmfs-sl6
```

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
@gaede @EnginEren FYI

**Comment by EnginEren** [comment]
That's really cool Remi! To be honest, I was afraid of this `--privileged` stuff. This is the only option for the local desktop/laptop.  For instance, if I tried to run this in maxwell, I would be banished/cursed by IT guys :) 

I will give a try to run this with `singularity` in NAF / maxwell. 

PS: there is no installation of docker in NAF as far as I know. Only `singularity`

**Comment by rete** [comment]
This installation is mainly meant to be used on private PC. It's light because it doesn't contain the full stack and usually you have the root password (thus privileges) on these machines. The image I think is only 1 Gb

**Comment by rete** [comment]
Also, CVMFS is installed in the image, but only mounted when a container is created. If you have issues providing the flag `--privileged`, then docker will complain first. Also if you don't give it then CVMFS mount will fail with an explicit error on container startup.

**Comment by gaede** [comment]
@rete just saw that you merged this already - nice.  Anyways, I think it would be good to add an example to the README for the usage where one mounts local disks to actually have access to data files to process and also be able to write out results...

**Comment by rete** [comment]
@gaede I put a bit more extended documentation for users here: https://hub.docker.com/repository/docker/ilcsoft/ilcsoft-cvmfs-sl6
This link is also in the release notes. The readme in iLCInstall is for developper only, how to regenerate the image, quick instructions how to run it, ... not really user oriented (on purpose). Tell me what you think about this link

**Pull request merged**
